name: Discord Alert System  # Nome do workflow

on:  # Quando o workflow ser치 acionado?
  push:  # Quando houver push (envio de c칩digo)
    branches: [ main ]  # Apenas na branch main
  pull_request:  # Quando houver uma pull request
    branches: [ main ]

jobs:  # Tarefas a serem executadas
  alert:  # Nome da tarefa
    runs-on: ubuntu-latest  # Sistema operacional usado
    steps:  # Passos da tarefa
    - name: Send Discord Alert  # Nome do passo
      uses: Ilshidur/action-discord@master  # A칞칚o pronta do GitHub
      env:  # Vari치veis de ambiente
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}  # Segredo configurado no GitHub
      with:  # Par칙metros
        args: "游뚿 Novo push detectado! Revis칚o necess치ria em: ${{ github.event.repository.url }}"  # Mensagem personalizada