name: Python Tests  # Nome do workflow

on: [pull_request]  # Executa quando houver uma pull request

jobs:
  build:  # Tarefa principal
    runs-on: ubuntu-latest  # Sistema operacional
    steps:  # Passos sequenciais
    - uses: actions/checkout@v2  # Baixa o código do repositório
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Versão do Python
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Atualiza o pip
    - name: Run tests
      run: |
        python -m unittest discover tests  # Executa os testes